# Generated by Django 2.2.6 on 2022-04-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=255, unique=True)),
                ('capacity_room', models.SmallIntegerField()),
                ('projector_available', models.BooleanField(default=False)),
            ],
        ),
    ]
